### PR TITLE
Added a tool to update and generate FontAwesomeIcons definition

### PR DESCRIPTION
**Pull request by pplante**
* Added `tool/generate_font.sh` which generates the `FontAwesomeIcons` class from the `icons.json` file published in the FontAwesome repository.
* Added `tool/update.sh` to download TTF & JSON files, execute the generator, and format the generated source code with dartfmt.
* Moved the `IconData` classes to `lib/_fonts.dart` so they do not get clobbered by the generator.
* Updated to FontAwesome 5.0.13
* Added updating section to README.md

### CODE REVIEW

**Comment by pplante** [comment]
I didn't really want to update to the latest FontAwesome within this pull request, however I couldn't figure out a way around this since I had to modify the way the library was structured slightly.  One idea I had was to have the `_fonts.dart` file live in another directory as a template, and then merge the content into the generated `font_awesome_flutter.dart` file.  Not really sure that is worth it.

**Comment by brianegan** [comment]
Amazing work -- I was planning on looking at how this type of auto-generation could be done, but hadn't seen that json file!

Thanks so much for the wonderful contribution. This will make maintenance far easier in the future.

**Comment by brianegan** [comment]
One heads up: The original script was not downloading the font files properly since Curl wasn't following redirects. Adding the `-L` flag to the curl commands for downloading fonts fixed the issue for me.

Thanks again for the awesome contribution! I've now extended it to generate the example package as well :)

**Comment by brianegan** [comment]
Just pushed these changes up as version 7.0.0 and added you to the Contributors in the README!

**Pull request merged**
